/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hikingsafety;

/**
 *
 * @author melanie
 */
public class TabbedForm extends javax.swing.JFrame {

    /**
     * Creates new form TabbedForm
     */
    public TabbedForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activityInformation = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        trailParkInfoLabel = new javax.swing.JLabel();
        trailParkInfoText = new javax.swing.JScrollPane();
        medImpInfoText = new javax.swing.JTextArea();
        TrailParkInfoDescr = new javax.swing.JLabel();
        groupAmtLabel = new javax.swing.JLabel();
        groupAmt = new javax.swing.JLabel();
        groupLeaderMainLabel = new javax.swing.JLabel();
        groupLeaderMainText = new javax.swing.JLabel();
        tripStartDateLabel = new javax.swing.JLabel();
        tripStartDateText = new javax.swing.JTextField();
        tripStartTimeLabel = new javax.swing.JLabel();
        tripStartTimeText = new javax.swing.JTextField();
        tripStartInfoLabel = new javax.swing.JLabel();
        tripEndTimeText = new javax.swing.JTextField();
        tripEndTimeLabel = new javax.swing.JLabel();
        tripEndDateText = new javax.swing.JTextField();
        tripEndDateLabel = new javax.swing.JLabel();
        tripEndInfoLabel = new javax.swing.JLabel();
        lengthTripLabel = new javax.swing.JLabel();
        numDaysInt = new javax.swing.JLabel();
        hikeIntensityLabel = new javax.swing.JLabel();
        hikeIntensityOptions = new javax.swing.JComboBox<>();
        hikingSafetyTitle = new javax.swing.JLabel();
        participantsTabs = new javax.swing.JTabbedPane();
        hikerTab1 = new javax.swing.JPanel();
        fNameText1 = new javax.swing.JTextField();
        fNameLabel1 = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        phoneNumberText1 = new javax.swing.JTextField();
        fullAddressText1 = new javax.swing.JTextField();
        fullAddressLabel1 = new javax.swing.JLabel();
        medImpInfoLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medImpInfoText1 = new javax.swing.JTextArea();
        lNameLabel1 = new javax.swing.JLabel();
        lNameText2 = new javax.swing.JTextField();
        leaderLabel1 = new javax.swing.JLabel();
        leaderOptions1 = new javax.swing.JComboBox<>();
        bmiInfoTitle1 = new javax.swing.JLabel();
        weightLabel1 = new javax.swing.JLabel();
        weightInt1 = new javax.swing.JTextField();
        weightLbsLabel1 = new javax.swing.JLabel();
        heightLabel1 = new javax.swing.JLabel();
        heightInt1 = new javax.swing.JTextField();
        heightInLabel1 = new javax.swing.JLabel();
        calcBMILabel1 = new javax.swing.JLabel();
        calcBMIInt1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        genderOption1 = new javax.swing.JComboBox<>();
        ageLabel1 = new javax.swing.JLabel();
        ageInt1 = new javax.swing.JTextField();
        fitnessLvlLabel1 = new javax.swing.JLabel();
        fitnessLvlOptions1 = new javax.swing.JComboBox<>();
        hikerTab2 = new javax.swing.JPanel();
        hikerTab3 = new javax.swing.JPanel();
        hikerTab4 = new javax.swing.JPanel();
        hikerTab5 = new javax.swing.JPanel();
        hikerTab6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trailParkInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        trailParkInfoLabel.setText("Trail/Park Information:");

        medImpInfoText.setColumns(20);
        medImpInfoText.setRows(5);
        trailParkInfoText.setViewportView(medImpInfoText);

        TrailParkInfoDescr.setFont(new java.awt.Font("Lucida Grande", 2, 8)); // NOI18N
        TrailParkInfoDescr.setText("This could include information such as the name of the trail, the address of the park, or a link to a map online.");

        groupAmtLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        groupAmtLabel.setText("Number of Participants:");

        groupAmt.setText("0");

        groupLeaderMainLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        groupLeaderMainLabel.setText("Group Leader:");

        groupLeaderMainText.setText("_________________________");

        tripStartDateLabel.setText("Date:");

        tripStartDateText.setText("00/00/2016");

        tripStartTimeLabel.setText("Time:");

        tripStartTimeText.setText("00:00");
        tripStartTimeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripStartTimeTextActionPerformed(evt);
            }
        });

        tripStartInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tripStartInfoLabel.setText("Trip Depart Information");

        tripEndTimeText.setText("00:00");
        tripEndTimeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripEndTimeTextActionPerformed(evt);
            }
        });

        tripEndTimeLabel.setText("Time:");

        tripEndDateText.setText("00/00/2016");

        tripEndDateLabel.setText("Date:");

        tripEndInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tripEndInfoLabel.setText("Trip Return Information");

        lengthTripLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lengthTripLabel.setText("Length of Trip:");

        numDaysInt.setText("0 days");

        hikeIntensityLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        hikeIntensityLabel.setText("Hike Intensity:");

        hikeIntensityOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Less Active", "Moderately Active", "Very Active", "Extremely Active" }));
        hikeIntensityOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeIntensityOptionsActionPerformed(evt);
            }
        });

        hikingSafetyTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        hikingSafetyTitle.setText("Hiker Buddy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrailParkInfoDescr)
                    .addComponent(trailParkInfoLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(groupAmtLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(groupAmt))
                                .addComponent(tripStartInfoLabel))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(groupLeaderMainLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(groupLeaderMainText))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(tripStartDateLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(tripStartDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tripStartTimeLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(tripStartTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tripEndInfoLabel)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lengthTripLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numDaysInt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(hikeIntensityLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(hikeIntensityOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(tripEndDateLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(tripEndDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tripEndTimeLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(tripEndTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(trailParkInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(hikingSafetyTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(hikingSafetyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trailParkInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trailParkInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrailParkInfoDescr)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupAmtLabel)
                    .addComponent(groupAmt)
                    .addComponent(groupLeaderMainLabel)
                    .addComponent(groupLeaderMainText))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripStartDateLabel)
                    .addComponent(tripStartDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripStartTimeLabel)
                    .addComponent(tripStartTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripStartInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripEndDateLabel)
                    .addComponent(tripEndDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripEndTimeLabel)
                    .addComponent(tripEndTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripEndInfoLabel))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthTripLabel)
                    .addComponent(numDaysInt)
                    .addComponent(hikeIntensityLabel)
                    .addComponent(hikeIntensityOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        activityInformation.addTab("Activity Information", jPanel1);

        fNameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameText1ActionPerformed(evt);
            }
        });

        fNameLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fNameLabel1.setText("First Name:");

        phoneNumberLabel1.setText("Phone Number:");

        phoneNumberText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberText1ActionPerformed(evt);
            }
        });

        fullAddressText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullAddressText1ActionPerformed(evt);
            }
        });

        fullAddressLabel1.setText("Full Address:");

        medImpInfoLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        medImpInfoLabel1.setText("Medical Conditions/Important Information:");

        medImpInfoText1.setColumns(20);
        medImpInfoText1.setRows(5);
        jScrollPane1.setViewportView(medImpInfoText1);

        lNameLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lNameLabel1.setText("Last Name:");

        lNameText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameText2ActionPerformed(evt);
            }
        });

        leaderLabel1.setText("Group Leader:");

        leaderOptions1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        bmiInfoTitle1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bmiInfoTitle1.setText("BMI Information:");

        weightLabel1.setText("Weight:");

        weightInt1.setText("0");
        weightInt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightInt1ActionPerformed(evt);
            }
        });

        weightLbsLabel1.setText("lbs.");

        heightLabel1.setText("Height:");

        heightInt1.setText("0");
        heightInt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightInt1ActionPerformed(evt);
            }
        });

        heightInLabel1.setText("in.");

        calcBMILabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        calcBMILabel1.setText("Calculated BMI:");

        calcBMIInt1.setText("0");

        jLabel1.setText("Gender:");

        genderOption1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unknown", "Male", "Female" }));

        ageLabel1.setText("Age:");

        ageInt1.setText(" ");
        ageInt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageInt1ActionPerformed(evt);
            }
        });

        fitnessLvlLabel1.setText("Fitness Level:");

        fitnessLvlOptions1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Intermediate", "Advanced" }));

        javax.swing.GroupLayout hikerTab1Layout = new javax.swing.GroupLayout(hikerTab1);
        hikerTab1.setLayout(hikerTab1Layout);
        hikerTab1Layout.setHorizontalGroup(
            hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hikerTab1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(hikerTab1Layout.createSequentialGroup()
                            .addComponent(phoneNumberLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(phoneNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leaderLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(leaderOptions1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                        .addComponent(medImpInfoLabel1)
                        .addGroup(hikerTab1Layout.createSequentialGroup()
                            .addComponent(fullAddressLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fullAddressText1))
                        .addGroup(hikerTab1Layout.createSequentialGroup()
                            .addComponent(fNameLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNameLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hikerTab1Layout.createSequentialGroup()
                        .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hikerTab1Layout.createSequentialGroup()
                                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bmiInfoTitle1)
                                    .addGroup(hikerTab1Layout.createSequentialGroup()
                                        .addComponent(weightLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(weightInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weightLbsLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(heightLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(heightInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hikerTab1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ageLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hikerTab1Layout.createSequentialGroup()
                                .addComponent(heightInLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(calcBMILabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcBMIInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hikerTab1Layout.createSequentialGroup()
                                .addComponent(fitnessLvlLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fitnessLvlOptions1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        hikerTab1Layout.setVerticalGroup(
            hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hikerTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel1)
                    .addComponent(fNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameLabel1)
                    .addComponent(lNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel1)
                    .addComponent(phoneNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaderLabel1)
                    .addComponent(leaderOptions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullAddressLabel1)
                    .addComponent(fullAddressText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medImpInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(genderOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel1)
                    .addComponent(ageInt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fitnessLvlLabel1)
                    .addComponent(fitnessLvlOptions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bmiInfoTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hikerTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLabel1)
                    .addComponent(weightInt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLbsLabel1)
                    .addComponent(heightLabel1)
                    .addComponent(heightInt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightInLabel1)
                    .addComponent(calcBMILabel1)
                    .addComponent(calcBMIInt1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        participantsTabs.addTab("Hiker #1", hikerTab1);

        javax.swing.GroupLayout hikerTab2Layout = new javax.swing.GroupLayout(hikerTab2);
        hikerTab2.setLayout(hikerTab2Layout);
        hikerTab2Layout.setHorizontalGroup(
            hikerTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        hikerTab2Layout.setVerticalGroup(
            hikerTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        participantsTabs.addTab("Hiker #2", hikerTab2);

        javax.swing.GroupLayout hikerTab3Layout = new javax.swing.GroupLayout(hikerTab3);
        hikerTab3.setLayout(hikerTab3Layout);
        hikerTab3Layout.setHorizontalGroup(
            hikerTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        hikerTab3Layout.setVerticalGroup(
            hikerTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        participantsTabs.addTab("Hiker #3", hikerTab3);

        javax.swing.GroupLayout hikerTab4Layout = new javax.swing.GroupLayout(hikerTab4);
        hikerTab4.setLayout(hikerTab4Layout);
        hikerTab4Layout.setHorizontalGroup(
            hikerTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        hikerTab4Layout.setVerticalGroup(
            hikerTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        participantsTabs.addTab("Hiker #4", hikerTab4);

        javax.swing.GroupLayout hikerTab5Layout = new javax.swing.GroupLayout(hikerTab5);
        hikerTab5.setLayout(hikerTab5Layout);
        hikerTab5Layout.setHorizontalGroup(
            hikerTab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        hikerTab5Layout.setVerticalGroup(
            hikerTab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        participantsTabs.addTab("Hiker #5", hikerTab5);

        javax.swing.GroupLayout hikerTab6Layout = new javax.swing.GroupLayout(hikerTab6);
        hikerTab6.setLayout(hikerTab6Layout);
        hikerTab6Layout.setHorizontalGroup(
            hikerTab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        hikerTab6Layout.setVerticalGroup(
            hikerTab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        participantsTabs.addTab("Hiker #6", hikerTab6);

        activityInformation.addTab("Participants", participantsTabs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(activityInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(activityInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameText1ActionPerformed

    private void phoneNumberText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberText1ActionPerformed

    private void fullAddressText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullAddressText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullAddressText1ActionPerformed

    private void lNameText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameText2ActionPerformed

    private void weightInt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightInt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightInt1ActionPerformed

    private void heightInt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightInt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightInt1ActionPerformed

    private void ageInt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageInt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageInt1ActionPerformed

    private void tripStartTimeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripStartTimeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripStartTimeTextActionPerformed

    private void tripEndTimeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripEndTimeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripEndTimeTextActionPerformed

    private void hikeIntensityOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeIntensityOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hikeIntensityOptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TrailParkInfoDescr;
    private javax.swing.JTabbedPane activityInformation;
    private javax.swing.JTextField ageInt1;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JLabel bmiInfoTitle1;
    private javax.swing.JLabel calcBMIInt1;
    private javax.swing.JLabel calcBMILabel1;
    private javax.swing.JLabel fNameLabel1;
    private javax.swing.JTextField fNameText1;
    private javax.swing.JLabel fitnessLvlLabel1;
    private javax.swing.JComboBox<String> fitnessLvlOptions1;
    private javax.swing.JLabel fullAddressLabel1;
    private javax.swing.JTextField fullAddressText1;
    private javax.swing.JComboBox<String> genderOption1;
    private javax.swing.JLabel groupAmt;
    private javax.swing.JLabel groupAmtLabel;
    private javax.swing.JLabel groupLeaderMainLabel;
    private javax.swing.JLabel groupLeaderMainText;
    private javax.swing.JLabel heightInLabel1;
    private javax.swing.JTextField heightInt1;
    private javax.swing.JLabel heightLabel1;
    private javax.swing.JLabel hikeIntensityLabel;
    private javax.swing.JComboBox<String> hikeIntensityOptions;
    private javax.swing.JPanel hikerTab1;
    private javax.swing.JPanel hikerTab2;
    private javax.swing.JPanel hikerTab3;
    private javax.swing.JPanel hikerTab4;
    private javax.swing.JPanel hikerTab5;
    private javax.swing.JPanel hikerTab6;
    private javax.swing.JLabel hikingSafetyTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNameLabel1;
    private javax.swing.JTextField lNameText2;
    private javax.swing.JLabel leaderLabel1;
    private javax.swing.JComboBox<String> leaderOptions1;
    private javax.swing.JLabel lengthTripLabel;
    private javax.swing.JLabel medImpInfoLabel1;
    private javax.swing.JTextArea medImpInfoText;
    private javax.swing.JTextArea medImpInfoText1;
    private javax.swing.JLabel numDaysInt;
    private javax.swing.JTabbedPane participantsTabs;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JTextField phoneNumberText1;
    private javax.swing.JLabel trailParkInfoLabel;
    private javax.swing.JScrollPane trailParkInfoText;
    private javax.swing.JLabel tripEndDateLabel;
    private javax.swing.JTextField tripEndDateText;
    private javax.swing.JLabel tripEndInfoLabel;
    private javax.swing.JLabel tripEndTimeLabel;
    private javax.swing.JTextField tripEndTimeText;
    private javax.swing.JLabel tripStartDateLabel;
    private javax.swing.JTextField tripStartDateText;
    private javax.swing.JLabel tripStartInfoLabel;
    private javax.swing.JLabel tripStartTimeLabel;
    private javax.swing.JTextField tripStartTimeText;
    private javax.swing.JTextField weightInt1;
    private javax.swing.JLabel weightLabel1;
    private javax.swing.JLabel weightLbsLabel1;
    // End of variables declaration//GEN-END:variables
}
